### ISSUE TITLE
System.registerDynamic is not a function

### ISSUE THREAD

**Issue by joshua1** [bnavetta/polymer-aurelia-web-app#1]
Hi @roguePanda 
I was trying to use your setup but kept getting this error in bundle.js 
`Uncaught TypeError: System.registerDynamic is not a function`
what could be the cause of this

**Comment by bnavetta** [comment]
I'll take a look. In the meantime, you might have better luck with [roguePanda/skeleton-navigation-polymer](https://github.com/roguePanda/skeleton-navigation-polymer), since it's a more standard Aurelia setup.

**Comment by bnavetta** [comment]
I think this is fixed, but now I'm getting errors about Aurelia's BindingLanguage implementation. Until bundling Aurelia applications is more stable, I'd suggest the repo I mentioned above.

**Comment by joshua1** [comment]
Thanks @roguePanda
