### ISSUE TITLE
Vulcanise Support

### ISSUE THREAD

**Issue by TomFoyster** [bnavetta/polymer-aurelia-web-app#2]
Does this project take advantage of Vulcanise to bundle Polymer includes? The Readme states so, however I can't see any evidence of it in the Gulp build process.

**Comment by bnavetta** [comment]
It does, in [`tool/tasks/html.js`](https://github.com/roguePanda/polymer-aurelia-web-app/blob/aurelia/tool/tasks/html.js#L25-L36). I haven't really been keeping this repository up to date, so there could be a better way to use it.
